### PR TITLE
zh: add the doc about Ad hoc mode for TiDB-Lightning

### PR DESCRIPTION
**Pull request by Joyinqin**
### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)
Add the doc about Ad-hoc mode for TiDB-Lightning helm chart.

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-tidb-operator/pull/956
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by csuzhangxc — APPROVED** [review]
LGTM

**Comment by ran-huang** [comment]
Somehow @BinChenn translated the text in https://github.com/pingcap/docs-tidb-operator/pull/912 😂
@Joyinqin I'll close this PR now. 

Thank you both for the translation!

**Pull request closed without merging**
