### PR TITLE
Include TiDB v5.0 in supported versions

### PR DESCRIPTION
**Pull request by dveeden**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)

TiDB v5.0 wasn't included in the list of supported versions

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by qiancai** [comment]
Hi @DanielZhangQD, would you please help confirm whether TiDB Operator v1.1 and v1.2 versions support TiDB 5.0 for now? Thanks!

**Comment by DanielZhangQD** [comment]
> Hi @DanielZhangQD, would you please help confirm whether TiDB Operator v1.1 and v1.2 versions support TiDB 5.0 for now? Thanks!

@qiancai Yes, both v1.1 and v1.2 support TiDB v5.0.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Review by qiancai — APPROVED** [review]

**Review by yikeke — APPROVED** [review]

**Pull request merged**
