### PR TITLE
Media: Delete images that involve third-party logos

### PR DESCRIPTION
**Pull request by Joyinqin**
### What is changed, added or deleted? (Required)
Delete the images that involve third-party logos and are not in the official doc.

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [x] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by ran-huang** [comment]
Deleting the image files will result in docs display failure. Is this expected?

**Comment by TomShawn** [comment]
@ran-huang The two images have third-party logos and need to be deleted or processed. I searched every branch of this repo and found that only v1.0 docs reference the two images. So it seems we can delete them on the `master` and `v1.1` branch.

@Joyinqin We still need to process the two images on v1.0 branch.

**Review by TomShawn — APPROVED** [review]
LGTM

**Pull request merged**
