### PR TITLE
en: updated docs links to stable instead of version-specific URLs

### PR DESCRIPTION
**Pull request by kolbe**
### What is changed, added or deleted? (Required)

A bunch of links in the tidb-operator documentation point back to the "main" PingCAP docs, but they were pointing to specific versions (v3.0, v3.1) instead of to "stable". This PR updates links to point to "stable" URLs.

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

Leaving v1.0 out of this since it isn't really even supposed to work with "stable" releases of the product.

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s):

### CODE REVIEW

**Comment by ran-huang** [comment]
@kolbe Could you please sign the CLA so that we can merge this pull request? 😀

**Comment by kolbe** [comment]
> @kolbe Could you please sign the CLA so that we can merge this pull request? 😀

I'm sure I've signed it before, but I did it again. Now it's stuck waiting for status to be reported. I think the poor CLA service is not running so well lately.

**Comment by ran-huang** [comment]
@kolbe Because the new website cannot parse `stable` urls for now, (as discussed in WeChat today), I'll merge this PR as soon as that issue is fixed. Is that acceptable for you?

**Pull request merged**
