### PR TITLE
Add scripts to verify link anchors

### PR DESCRIPTION
**Pull request by yikeke**
### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [x] v1.0 (TiDB Operator 1.0 versions)

I will manually cherry-pick this PR to release-1.0.

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s):  https://github.com/pingcap/docs-dm/pull/146/

### CODE REVIEW

**Comment by ran-huang** [comment]
@DanielZhangQD This script is used to verify link anchors in this repo. I fixed most of the dead anchors except this:
```
zh/tidb-operator-overview.md
  47:3-47:56  warning  Dead anchor: upgrade-a-tidb-cluster.md#更新-tidb-集群配置
```
That section `#更新-tidb-集群配置` was moved to a new doc by this PR (https://github.com/pingcap/docs-tidb-operator/pull/366). Please help find out how to fix this anchor.

**Comment by DanielZhangQD** [comment]
> #366

@ran-huang Sorry that I missed this message. Please update to `configure-cluster-using-tidbcluster.md`.

**Pull request merged**
