### PR TITLE
zh: Support BR on Azure Blob Storage

### LINKED ISSUE #1892: Support BR on Azure Blob Storage
## Change Request

**This repository is ONLY used to solve issues related to TiDB Operator documentation.
For other issues (related to TiDB, PD, etc), please move to [other repositories](https://github.com/pingcap/).**

Please answer the following questions before submitting your issue. Thanks!

1. Describe what you find is inappropriate or missing in the existing docs.
Refer to  #https://github.com/pingcap/tidb-operator/pull/4534

2. Describe your suggestion or addition.

3. Provide some reference materials (documents, websites, etc) if you could.

### PR DESCRIPTION
**Pull request by xu21yingan**
Closes #1892

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)
Added - Support BR on Azure Blob Storage

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.3 (TiDB Operator 1.3 versions)
- [ ] v1.2 (TiDB Operator 1.2 versions)
- [ ] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s):  https://github.com/pingcap/tidb-operator/pull/4534

### CODE REVIEW

**Review by ran-huang — COMMENTED** [review]
Just some minor comments. Rest LGTM.

**Review by KanShiori — APPROVED** [review]

**Review by ran-huang — APPROVED** [review]

**Pull request merged**
