### PR TITLE
zh: remove dead link for tiflash

### PR DESCRIPTION
**Pull request by dragonly**
### What is changed, added or deleted? (Required)

remove dead link for deploying tiflash

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

None

### Do your changes match any of the following descriptions?

None

### CODE REVIEW

**Comment by dragonly** [comment]
fixed issue #805

**Review by ran-huang — APPROVED** [review]

**Pull request merged**
