### PR TITLE
en,zh; Bump tidb components to v5.0.1

### PR DESCRIPTION
**Pull request by csuzhangxc**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)

en,zh; Bump tidb components to v5.0.1

ref #1160 

Run commands:

```sh
find . -type f | xargs sed -i "s/v4.0.10/v5.0.1/g"
# do NOT update release notes
git checkout -- zh/releases en/releases
```

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by qiancai** [comment]
Hi @csuzhangxc, would you please help confirm if the same change is also applicable for v1.1? Thanks~

**Comment by csuzhangxc** [comment]
> Hi @csuzhangxc, would you please help confirm if the same change is also applicable for v1.1? Thanks~

Think only for master now.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
