### PR TITLE
en, zh: change "Region" capitalization

### PR DESCRIPTION
**Pull request by ran-huang**
Signed-off-by: Ran <huangran@pingcap.com>

### What is changed, added, or deleted? (Required)

Change "Region" to "region" for those cases of referring to a geographical location, to differentiate it from the "Region" (data segment) concept in the TiDB database.
a cherry-pick of https://github.com/pingcap/docs-tidb-operator/pull/1127

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Review by lilin90 — COMMENTED** [review]
/lgtm

**Comment by ran-huang** [comment]
> /lgtm

@lilin90 It seems not working. You need to comment `/lgtm` **in the comment box at the bottom of the PR** or use Approve directly.

**Pull request merged**
