### PR TITLE
Update deploy-on-aws-eks.md

### PR DESCRIPTION
**Pull request by xinghua0123**
Added the detailed YAML file for TiDB cluster and links for advanced configurations and explanations for API

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by ran-huang** [comment]
@xinghua0123 Thank you for your contribution! 
May I know why you made this change?

**Comment by xinghua0123** [comment]
> @xinghua0123 Thank you for your contribution!
> May I know why you made this change?

@ran-huang Thanks for your reply.
It's just to make the official document more complete as readers may want to know what's actually included in the tidb-cluster.yaml file which he deployed and also some customizations they can make. So I added the reference link as well.

**Comment by ran-huang** [comment]
> @ran-huang Thanks for your reply.
> It's just to make the official document more complete as readers may want to know what's actually included in the tidb-cluster.yaml file which he deployed and also some customizations they can make. So I added the reference link as well.

@xinghua0123 You're right! We do need to provide more info for concerned readers.
However, the yaml file is a bit long and perhaps distracting for other readers. How about we just point readers to the reference link?

BTW—`deploy-on-gcp-gke.md` and `deploy-on-alibaba-cloud.md` have the same section. Do you mind adding them as well?

**Comment by DanielZhangQD** [comment]
> > @ran-huang Thanks for your reply.
> > It's just to make the official document more complete as readers may want to know what's actually included in the tidb-cluster.yaml file which he deployed and also some customizations they can make. So I added the reference link as well.
> 
> @xinghua0123 You're right! We do need to provide more info for concerned readers.
> However, the yaml file is a bit long and perhaps distracting for other readers. How about we just point readers to the reference link?
> 
> BTW—`deploy-on-gcp-gke.md` and `deploy-on-alibaba-cloud.md` have the same section. Do you mind adding them as well?

@xinghua0123 as @ran-huang  has suggested, 

- Let's just add a link to the https://docs.pingcap.com/tidb-in-kubernetes/dev/configure-a-tidb-cluster doc here before applying the yamls, we may have to update the commands to let the user download the example yaml first and then ask the user to refer to the `configure-a-tidb-cluster` doc to configure the CR and then apply the yamls.
- Please also help update the doc for GKE and ACK.
- 

Thanks!

**Comment by xinghua0123** [comment]
Will submit a new PR

**Pull request closed without merging**
