### PR TITLE
.github: add external link check

### PR DESCRIPTION
**Pull request by yikeke**
### What is changed, added or deleted? (Required)

A migration from https://github.com/pingcap/docs-dm/pull/353

**Note** this external link check isn't required to pass, in order to prevent false alarms from blocking PR merge.

The current regex exclusions is: 

`http://172.*|https://github.com/.*/pull/.*|https://github.com/.*/issues/.*|https://github.com/[^.\n]*$|http://127.0.0.1.*|http://localhost.*|.*.md`

Meaning **the check will skip checking the URLs matching the above patterns**.

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v1.1 (TiDB Operator 1.1 versions)
- [x] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

### CODE REVIEW

**Comment by yikeke** [comment]
There are many github bad requests being reported. I think we only need to check github links with a file name suffix such as `https://github.com/pingcap/tidb-operator/blob/master/manifests/monitor/tidb-monitor.yaml` or `https://github.com/pingcap/tidb/blob/master/config/config.toml.example`, and links to someone's repo or an issue can be ignored.

Or we can skip checking releases/release-xxx.md files because in the files there are many links that can be ignored.

Do you have some clue to exclude the reported github links?  @csuzhangxc

**Comment by csuzhangxc** [comment]
> There are many github bad requests being reported. I think we only need to check github links with a file name suffix such as `https://github.com/pingcap/tidb-operator/blob/master/manifests/monitor/tidb-monitor.yaml` or `https://github.com/pingcap/tidb/blob/master/config/config.toml.example`, and links to someone's repo or an issue can be ignored.
> 
> Or we can skip checking releases/release-xxx.md files because in the files there are many links that can be ignored.
> 
> Do you have some clue to exclude the reported github links? @csuzhangxc

[liche](https://github.com/raviqqe/liche) (the tool used in `peter-evans/link-checker@v1`) can ignore links which match a specified pattern (as you did for `https://github.com/pingcap/tidb-operator/pull/.*`).

but in this repo, maybe you can remove `-r` from `args` to disable `recursive` search for files, then `zh/releases`/`en/releases` may be ignored. for more advanced usage, you may need to ref <http://docopt.org/> (I haven't read it).

**Comment by yikeke** [comment]
> > There are many github bad requests being reported. I think we only need to check github links with a file name suffix such as `https://github.com/pingcap/tidb-operator/blob/master/manifests/monitor/tidb-monitor.yaml` or `https://github.com/pingcap/tidb/blob/master/config/config.toml.example`, and links to someone's repo or an issue can be ignored.
> > Or we can skip checking releases/release-xxx.md files because in the files there are many links that can be ignored.
> > Do you have some clue to exclude the reported github links? @csuzhangxc
> 
> [liche](https://github.com/raviqqe/liche) (the tool used in `peter-evans/link-checker@v1`) can ignore links which match a specified pattern (as you did for `https://github.com/pingcap/tidb-operator/pull/.*`).
> 
> but in this repo, maybe you can remove `-r` from `args` to disable `recursive` search for files, then `zh/releases`/`en/releases` may be ignored. for more advanced usage, you may need to ref http://docopt.org/ (I haven't read it).

Okay, I'll look into that. Thanks~

**Comment by yikeke** [comment]
The `external-link-check` check found two 404s:

- zh/enable-admission-webhook.md: https://kubernetes.io/zh/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#%E5%90%AF%E7%94%A8-kubernetes-apiserver-%E6%A0%87%E5%BF%97 Not Found (HTTP error 404)
- en/configure-a-tidb-cluster.md: https://pingcap.com/docs/stable/ticdc/deploy-ticdc/#manually-add-ticdc-component-to-an-existing-tidb-cluster Not Found (HTTP error 404)

Could you help fix them? @ran-huang

**Comment by ran-huang** [comment]
> The `external-link-check` check found two 404s:
> 
> * zh/enable-admission-webhook.md: https://kubernetes.io/zh/docs/tasks/access-kubernetes-api/configure-aggregation-layer/#%E5%90%AF%E7%94%A8-kubernetes-apiserver-%E6%A0%87%E5%BF%97 Not Found (HTTP error 404)
> * en/configure-a-tidb-cluster.md: https://pingcap.com/docs/stable/ticdc/deploy-ticdc/#manually-add-ticdc-component-to-an-existing-tidb-cluster Not Found (HTTP error 404)
> 
> Could you help fix them? @ran-huang

Sure.

**Review by ran-huang — APPROVED** [review]
LGTM

**Pull request merged**
