### PR TITLE
en,zh: fix wrong dmctl command

### PR DESCRIPTION
**Pull request by lance6716**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)

dmctl can't support `http://` as master addr. close https://github.com/pingcap/dm/issues/1459

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: 
- Other reference link(s): 

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

### CODE REVIEW

**Comment by ran-huang** [comment]
/translation done
/sig migrate docs

@lance6716 Can you involve a tech reviewer?

**Comment by ran-huang** [comment]
FYI. `enable-tls-for-dm.md` is a doc for master only. This PR doesn't need to cherry-pick to other branches.

**Review by DanielZhangQD — APPROVED** [review]
LGTM

**Pull request merged**
