### PR TITLE
Update prerequisites.md

### PR DESCRIPTION
**Pull request by SuperSupeng**
### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-tidb-operator) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)
Add docker.service path

### What is the related PR or file link(s)?
- This PR is translated from:
- Other reference link(s):

### Which TiDB Operator version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v1.1 (TiDB Operator 1.1 versions)
- [ ] v1.0 (TiDB Operator 1.0 versions)

### CODE REVIEW

**Comment by KanShiori** [comment]
It will be solved by #1264

**Comment by qiancai** [comment]
Hi @SuperSupeng, thanks for the contribution to the TiDB Operator docs. According to the above reply from @KanShiori, this will be solved by https://github.com/pingcap/docs-tidb-operator/pull/1264. do you think we can close this PR?

**Comment by SuperSupeng** [comment]
> Hi @SuperSupeng, thanks for the contribution to the TiDB Operator docs. According to the above reply from @KanShiori, this will be solved by #1264. Do you think we can close this PR?

sure

**Pull request closed without merging**
